import { escapeHtml } from "../markdown.js";
import { t } from "../i18n.js";
import { layout } from "./layout.js";

function asObject(value: any) { return value && typeof value === "object" && !Array.isArray(value) ? value : {}; }
function stringList(value: any) { return Array.isArray(value) ? value.filter((item) => typeof item === "string") : []; }
function resetButton(reset: string) { return `<button type="button" class="settings-reset-btn" data-reset-setting="${escapeHtml(reset)}">${t("settings.reset_default")}</button>`; }
function field({ id, label, value = "", help = "", reset = "" }: any) { return `<div class="settings-field"><div class="settings-field-heading"><label for="${id}">${escapeHtml(label)}</label>${reset ? resetButton(reset) : ""}</div><input id="${id}" type="text" value="${escapeHtml(value)}">${help ? `<small>${escapeHtml(help)}</small>` : ""}</div>`; }
function textareaField({ id, label, values = [], help = "", placeholder = "", reset = "" }: any) { return `<div class="settings-field"><div class="settings-field-heading"><label for="${id}">${escapeHtml(label)}</label>${reset ? resetButton(reset) : ""}</div><textarea id="${id}" rows="5" placeholder="${escapeHtml(placeholder)}">${escapeHtml(values.join("\n"))}</textarea>${help ? `<small>${escapeHtml(help)}</small>` : ""}</div>`; }
function switchField({ id, label, description, enabled, reset = "" }: any) { return `<div class="settings-switch-row"><label class="settings-switch" for="${id}"><span class="settings-switch-copy"><strong>${escapeHtml(label)}</strong><small>${escapeHtml(description)}</small></span><input id="${id}" type="checkbox" ${enabled ? "checked" : ""}><span class="settings-switch-track" aria-hidden="true"></span></label>${reset ? resetButton(reset) : ""}</div>`; }

export function renderSettingsPage({ configPath, configDocument, terminalLaunchAllowed = false, provider = "opencode", providerName = provider, resumeDefault = null, providers = [], providerAvailable = true, manageable = false }: any) {
  const config = asObject(configDocument.config);
  const projectPaths = asObject(asObject(config.projectPaths)[provider]);
  const projectPathLines = Object.entries(projectPaths).filter(([key, value]) => Boolean(String(key).trim()) && typeof value === "string" && value.trim()).sort(([left], [right]) => left.localeCompare(right)).map(([key, value]) => `${key}=${value}`);
  const configuredResume = asObject(config.resumeCommands)[provider];
  const resumeEnabled = configuredResume !== false;
  const resumeCommand = configuredResume && configuredResume !== false ? configuredResume : resumeDefault || { executable: "", args: [] };
  const resumeShell = asObject(config.resumeShell);
  const shellExecutable = typeof resumeShell.executable === "string" ? resumeShell.executable : "";
  const shellMode = ["", "pwsh.exe", "powershell.exe"].includes(shellExecutable) ? shellExecutable : "custom";
  const editorValue = configDocument.error ? configDocument.raw : `${JSON.stringify(config, null, 2)}\n`;
  const initialData = JSON.stringify({ provider, resumeDefault: resumeDefault || { executable: "", args: [] } }).replace(/</g, "\\u003c");
  const statusClass = terminalLaunchAllowed ? "settings-status-ok" : "settings-status-warn";
  const statusText = terminalLaunchAllowed ? t("settings.launch_enabled") : t("settings.launch_disabled");
  const body = `<section class="settings-page"><header class="page-header settings-page-header"><div><h1>${t("settings.title")}</h1><p>${t("settings.description")}</p></div><div class="settings-provider-pill">${escapeHtml(providerName)}</div></header>
    <div class="settings-status-grid"><section class="settings-card"><span class="settings-label">${t("settings.config_file")}</span><code class="settings-path">${escapeHtml(configPath)}</code></section><section class="settings-card"><span class="settings-label">${t("settings.launch_permission")}</span><strong class="${statusClass}">${escapeHtml(statusText)}</strong><p>${t("settings.launch_help")}</p></section></div>
    ${configDocument.error ? `<div class="settings-alert settings-alert-error"><strong>${t("settings.invalid_file")}</strong><span>${escapeHtml(configDocument.error)}</span></div>` : ""}
    <nav class="settings-section-nav" aria-label="${escapeHtml(t("settings.sections_nav"))}"><a href="#settings-project-paths">${t("settings.project_paths")}</a><a href="#settings-resume">${t("settings.resume_title")}</a><a href="#settings-advanced" data-open-settings-advanced>${t("settings.advanced_title")}</a></nav>
    <form id="settings-form" class="settings-form" data-provider="${escapeHtml(provider)}"><section class="settings-section" id="settings-project-paths"><div class="settings-section-header"><div><h2>${t("settings.project_paths")}</h2><p>${t("settings.project_paths_help")}</p></div></div>${textareaField({ id: "settings-project-paths-input", label: t("settings.project_paths"), values: projectPathLines, help: t("settings.project_paths_help"), placeholder: t("settings.project_paths_placeholder"), reset: "project-paths" })}</section>
      <section class="settings-section" id="settings-resume"><div class="settings-section-header"><div><h2>${t("settings.resume_title")}</h2><p>${t("settings.resume_description")}</p></div>${switchField({ id: "settings-resume-enabled", label: t("settings.resume_enabled"), description: t("settings.resume_enabled_help"), enabled: resumeEnabled, reset: "resume-enabled" })}</div><div class="settings-fields-grid">${field({ id: "settings-resume-executable", label: t("settings.executable"), value: resumeCommand.executable || "", reset: "resume-executable" })}${field({ id: "settings-resume-cwd", label: t("settings.working_directory"), value: resumeCommand.cwd || "", help: t("settings.working_directory_help"), reset: "resume-cwd" })}${textareaField({ id: "settings-resume-args", label: t("settings.arguments"), values: stringList(resumeCommand.args), help: t("settings.arguments_help"), reset: "resume-args" })}<div class="settings-field"><div class="settings-field-heading"><label for="settings-shell-mode">${t("settings.shell")}</label>${resetButton("shell-mode")}</div><select id="settings-shell-mode"><option value="" ${shellMode === "" ? "selected" : ""}>${t("settings.shell_auto")}</option><option value="pwsh.exe" ${shellMode === "pwsh.exe" ? "selected" : ""}>PowerShell 7 (pwsh.exe)</option><option value="powershell.exe" ${shellMode === "powershell.exe" ? "selected" : ""}>Windows PowerShell</option><option value="custom" ${shellMode === "custom" ? "selected" : ""}>${t("settings.shell_custom")}</option></select><small>${t("settings.shell_help")}</small></div><div class="settings-field ${shellMode === "custom" ? "" : "hidden"}" id="settings-shell-custom-field">${field({ id: "settings-shell-custom", label: t("settings.custom_executable"), value: shellMode === "custom" ? shellExecutable : "", reset: "shell-custom" })}</div>${textareaField({ id: "settings-shell-args", label: t("settings.shell_arguments"), values: stringList(resumeShell.args), help: t("settings.one_per_line"), reset: "shell-args" })}</div></section>
      <details class="settings-advanced" id="settings-advanced"><summary>${t("settings.advanced_title")}</summary><p>${t("settings.advanced_help")}</p><div class="settings-actions"><button type="button" class="btn" id="settings-format">${t("settings.format")}</button><button type="button" class="btn" id="settings-apply-json">${t("settings.apply_json")}</button></div><p id="settings-json-feedback" class="settings-json-feedback" role="status"></p><textarea id="settings-json" class="settings-json-editor" spellcheck="false" aria-label="${escapeHtml(t("settings.json_title"))}" aria-describedby="settings-json-feedback">${escapeHtml(editorValue)}</textarea></details>
      <div class="settings-save-bar"><div><p id="settings-feedback" class="settings-feedback" role="status"></p><span id="settings-dirty-state" class="settings-dirty-state" data-dirty="false">${t("settings.all_saved")}</span><span class="settings-runtime-note-inline">${t("settings.runtime_note")}</span></div><button type="submit" class="btn settings-save" disabled>${t("settings.save")}</button></div></form><script type="application/json" id="settings-initial-data">${initialData}</script></section>`;
  return layout(t("settings.title"), body, "settings", { provider, providers, providerAvailable, manageable });
}
